---
name: cleanup packages
on:
  schedule:
    - cron: '0 5 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  x86_64:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        include:
          image_name:
            - kamailio
            - kamailio-ci
            - kamailio-master-devcontainer
            - pkg-kamailio-docker
    steps:
    - name: Delete untagged images
      uses: camargo/delete-untagged-action@v1
      with:
        github-token: ${{ secrets.CLEAN_PACKAGES }}
        package-name: ${{ matrix.image_name }}
